export default {
  REQUEST_INITIAL_VALUE: 'REQUEST_INITIAL_VALUE',
  GET_INITIAL_VALUE: 'GET_INITIAL_VALUE',
  CHANGE_VALUE: 'CHANGE_VALUE',
  OPEN_PREFERENCES_WINDOW: 'OPEN_PREFERENCES_WINDOW',
  CHECK_OPEN_LOGIN: 'CHECK_OPEN_LOGIN',
  TOGGLE_OPEN_LOGIN: 'TOGGLE_OPEN_LOGIN',
  QUIT: 'QUIT',
};
